language: go
dist: trusty
go:
- 1.8
branches:
  only:
  - source
env:
  global:
  - SOURCE_DIR="public"
  - BUILD_BRANCH="source"
  - DEPLOY_BRANCH="master"
before_install:
- openssl aes-256-cbc -K $encrypted_8c8cc68a0de5_key -iv $encrypted_8c8cc68a0de5_iv
  -in travis-ci.enc -out travis-ci -d
- sudo apt-get -qq update
- eval "$(ssh-agent -s)"
- chmod 600 travis-ci
- ssh-add travis-ci
install:
- go get -u -v github.com/spf13/hugo
- git clone git@github.com:$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
- cd $TRAVIS_REPO_SLUG
script:
- "./scripts/merge.sh"
notifications:
  email: false
  slack:
    secure: MQv1/tMT4k/xlmhK58+UbGtza2FEeFmGQdqIRSEY/m1jcURP40caPVg8Jsb/bXH09o+bhGzSQlUDal1S/8RWjr1S96G9LpeWq3bcOc8WouNYfS6qkP5WPmKaQq/naU4XKt6KzDbWSZKx059YEgLm4/VoU1rDu//9qub646sqBYRTrXy+27B3tuC+zNTNeA7nbhXDD7jOAwv+NQQbInt200ea3m69pFZRKyUh7uZlSPOZPfxPzkgw6LZ4RGt9WnLpXTsaKrHU3QskBGUjC4P57UOAeLGGKc5IVedzWjRMXEInYvxPlRzukRN0keuFrNzqnEpv4dtGlHBiqyJCJaHKBqaCyua4tFJ1m82n2UOuA8SK29ZZqbG669MobvY2HI9V4kYVChQb8oSGAPFkRWULJDxjjo0ZuX0MQtEcZZxXAyHHKC75OEipQvT7Xtl+kJmE+qxgZRdr7HQ5TGXEqaoKY0BdnDcS66TQfT1dR6iPrBd6GiKgKKb4yZ2qbKXHJ34CWZi5n8BjIyuKGm7VBGXwUrmgcdRs7rqfSB1WXfuyx5a4krspgMGNEGuKH7PDRt+Ak6rXEPRKU1Xp9gma3la+eInMkCHWOPstQjYaqDrLKaytpCgyWUMcKbxzLqpvhuGbvxn6T5USnD/Zgre5wah4+BVX1ECMY0L2YNOkbGlonHU=
